# Generated by Django 5.2.5 on 2025-10-31 11:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('wallet_id', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('investor', 'Investor')], max_length=10)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='farms/')),
                ('size', models.DecimalField(decimal_places=2, help_text='Farm size in acres', max_digits=10)),
                ('crop_type', models.CharField(choices=[('coffee', 'Coffee'), ('maize', 'Maize'), ('rice', 'Rice'), ('wheat', 'Wheat'), ('avocado', 'Avocado'), ('tea', 'Tea'), ('cocoa', 'Cocoa'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('valuation', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField()),
                ('token_id', models.CharField(blank=True, max_length=50, null=True)),
                ('token_price', models.DecimalField(decimal_places=2, default=Decimal('125.00'), max_digits=10)),
                ('investors', models.PositiveIntegerField(default=0)),
                ('raised', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('expected_roi', models.FloatField(default=28.5)),
                ('status', models.CharField(default='pending', help_text='pending, active, funded, completed', max_length=50)),
                ('raised_in_cent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.PositiveIntegerField()),
                ('invested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currentValue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('roi', models.FloatField(default=28.5)),
                ('payment_method', models.CharField(choices=[('usd', 'USD'), ('hbar', 'HBAR')], max_length=10)),
                ('transaction_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='core.farm')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('investor', 'farm')},
            },
        ),
        migrations.CreateModel(
            name='ROIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_records', to='core.investment')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('method', models.CharField(choices=[('fiat', 'Fiat'), ('crypto', 'Crypto')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
